server:
  port: 9000
  application:
  name: ORDERING-SERVICE
eureka:
  client:
    service-url:
      default-zone: http://localhost:8671/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mojja
    username: mjhan
    password: mjhan

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update